### ISSUE TITLE
Project approval

### ISSUE THREAD

**Issue by CDSLabs** [sjsucmpe272-fall21/Team-Project-21-Cashflow#1]
all of your proposed project ideas have been implemented by my 272 students from the previous semesters. Here is the idea I am giving you guys:
Project: Cashflow
With a booming real estate market, more than 50% of transactions are investment homes. However, investors have a hard time figuring if a house in the market will have positive cash flow. Even if a price seems low, as you can see an example below, taxes, HOA, age of home, location can eat up most of the rental income. 
Create a web application called cashflow to determine which home will yield + cashflow and which will not ...
get data from Zillow or other sites, you may use Rent estimate from Zillow as well.

sample:
https://www.redfin.com/FL/Gainesville/4000-SW-23rd-St-32608/unit-6-207/home/115647438
As you can see, a 4Bed 4 Bath apt in Gainesville FL is on sale for only $159k with a rental income of let's say $1600 but when you add up the mortgage, property tax, HOA, etc... is there a cashflow?
You can do homework and discuss it with me with questions. This project is done right has startup potential.

**Comment by Navami10** [comment]
Hello Professor, 

Thank you so much for your feedback. 
It is a great idea and we are ready to proceed with it. 

Thank you.
